# Utiliser une image de base contenant Go
FROM golang:1.20

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers source dans le conteneur
COPY . .

# Compiler l'application
RUN go build -o ascii-art-web .

# Exposer le port sur lequel l'application écoute
EXPOSE 8080

# Définir la commande par défaut pour démarrer l'application
CMD ["./ascii-art-web"]
